name: Workflow evento Fluxo de Controle
on:
  push:

jobs:
  apenas-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Esse Job só executa na branch main
    runs-on: ubuntu-latest
    steps:
      - name: Executando na Main
        run: echo "Executando comando na Main"
  todos:
    runs-on: ubuntu-latest
    steps:
      - name: Execução em Feature
        if: ${{ contains(github.ref, 'refs/heads/feature') }}
        run: echo "Executando em Feature"
      - name: Execução em Hotfix
        if: ${{ contains(github.ref, 'refs/heads/hotfix') }}
        run: echo "Executando em Hotfix"
      - name: Execução em Main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "Executando em Main"
