name: Workflow evento Scheduled
on:
  schedule:
    - cron: "*/5 * * * *" # Executa diariamente à meia-noite

jobs:
  teste:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Action de Teste
        run: |
          echo "Action executada apenas em main e feature/*"
